@{
    PublicCmdlets = @{
        'Add-Attachment'          = @{ Covered = $false }
        'Add-Label'               = @{ Covered = $false }
        'ConvertTo-StorageFormat' = @{ Covered = $true }
        'ConvertTo-Table'         = @{ Covered = $true }
        'Get-Attachment'          = @{ Covered = $false }
        'Get-AttachmentFile'      = @{ Covered = $true }
        'Get-BlogPost'            = @{ Covered = $true }
        'Get-ChildPage'           = @{ Covered = $true }
        'Get-Database'            = @{ Covered = $true }
        'Get-Folder'              = @{ Covered = $true }
        'Get-FooterComment'       = @{ Covered = $true }
        'Get-InlineComment'       = @{ Covered = $true }
        'Get-InlineTask'          = @{ Covered = $true }
        'Get-Label'               = @{ Covered = $false }
        'Get-Page'                = @{ Covered = $true }
        'Get-PageAncestor'        = @{ Covered = $true }
        'Get-PageVersion'         = @{ Covered = $true }
        'Get-ServerInformation'   = @{ Covered = $true }
        'Get-Space'               = @{ Covered = $true }
        'Get-SpacePermission'     = @{ Covered = $true }
        'Get-SpaceProperty'       = @{ Covered = $true }
        'Get-SpaceRoleAssignment' = @{ Covered = $true }
        'Get-Whiteboard'          = @{ Covered = $true }
        'Invoke-Method'           = @{ Covered = $true }
        'New-BlogPost'            = @{ Covered = $true }
        'New-FooterComment'       = @{ Covered = $true }
        'New-InlineComment'       = @{ Covered = $true }
        'New-Page'                = @{ Covered = $false }
        'New-Space'               = @{ Covered = $false }
        'New-SpaceProperty'       = @{ Covered = $true }
        'Remove-Attachment'       = @{ Covered = $false }
        'Remove-BlogPost'         = @{ Covered = $true }
        'Remove-FooterComment'    = @{ Covered = $true }
        'Remove-InlineComment'    = @{ Covered = $true }
        'Remove-Label'            = @{ Covered = $false }
        'Remove-Page'             = @{ Covered = $false }
        'Remove-Space'            = @{ Covered = $false }
        'Remove-SpaceProperty'    = @{ Covered = $true }
        'Set-Attachment'          = @{ Covered = $false }
        'Set-BlogPost'            = @{ Covered = $true }
        'Set-FooterComment'       = @{ Covered = $true }
        'Set-InlineComment'       = @{ Covered = $true }
        'Set-InlineTask'          = @{ Covered = $true }
        'Set-Info'                = @{ Covered = $true }
        'Set-Label'               = @{ Covered = $false }
        'Set-Page'                = @{ Covered = $true }
        'Set-SpaceProperty'       = @{ Covered = $true }
        'Set-SpaceRoleAssignment' = @{ Covered = $true }
    }
}
